server.port=8081

# JWT настройки
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
app.jwt.header=Authorization
app.jwt.prefix=Bearer

# ---- имя приложения -------------------------------------------------
spring.application.name=lcmApp

# ---- подключение к PostgreSQL ---------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/lcm_material
spring.datasource.username=u0_a364
spring.datasource.password=lcmAll

# ---- JPA / Hibernate ------------------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Разрешить переопределение бинов
spring.main.allow-bean-definition-overriding=true

# ---- Логирование в файл ----------------------------------------------
logging.level.com.example.lcmApp.service=INFO
logging.file.name=logs/material-operations.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %-5level [%thread] %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n

# ---- Настройки ротации логов -----------------------------------------
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
